### ISSUE TITLE
[Android] Blank map

### ISSUE THREAD

**Issue by tomazahlin** [lelandrichardson/react-native-maps#176]
Hello, I have installed react-native-maps to our application, but had a problem where the <MapView> would render blank (like nothing was there).

After searching the repository for solutions, I haven't found anything that would work for me, but ultimately we found a solution. If anyone else has a problem, here is what we found out:

We use Android Virtual Device (AVD) Manager to start the emulator. Also make sure you install Intel HAXM 6.0.1.

1. Run "android" and install
Extras / Google Play services
Extras / Google Repository
Android 6.0 (API 23) / Google APIs Intel x86 Atom System Image Rev. 12 (Make sure your emulator is using it, previous rev. did not work)

2. Make sure that you use the "WEB" api key from Google.

3. When starting emulator before building the new native code, make sure you "Wipe user data".

Hopefully this will help someone. I think all the other steps are like described in docs. If I remember any more steps, I will write them here.

**Comment by christopherdro** [comment]
Can you try taking a look at #118 ?

**Comment by tomazahlin** [comment]
Looks like a similar issue, I will let the users know of my solution.

**Comment by KGALLET** [comment]
What do you mean by "WEB" api key?
We have to take it from Google Console API but the type of the key must be "Android", i'm right?

**Comment by tomazahlin** [comment]
Other developer in our company told me, to use "Browser or web" key, not some other key. It was a little confusing.

**Comment by magrinj** [comment]
@KGALLET & @tomazahlin: Maybe you can do a PR to update the documentation :)

**Comment by KGALLET** [comment]
@tomazahlin are you going to PR this ? If Not i can do it

**Comment by tomazahlin** [comment]
@KGALLET You can do it, I am currently working on another PR for another react module, and not sure when I have time. But if you need any more details from me, you can ask anytime.

**Comment by KGALLET** [comment]
Done. #179

**Comment by dhdo** [comment]
I did everything in the Installation Guide and everything in the Troubleshooting but i'm still getting the Blank Map issue, no error is shown in the console. 

Running on Mac with Android AVD (Android 6.0 (API 23) / Google APIs Intel x86 Atom System)
react-native-cli: 1.0.0
react-native: 0.27.2

Using the basic code: 
```javascript
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  View
} from 'react-native';

import MapView from 'react-native-maps';

class ReactMap extends Component {
  render() {
    return (

      <View style ={styles.container}>
        <MapView
          style={styles.map}
          region={
              latitude: 37.78825,
              longitude: -122.4324,
              latitudeDelta: 0.015,
              longitudeDelta: 0.0121,
          }
          >
        </MapView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    height: 400,
    width: 400,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  map: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
});


AppRegistry.registerComponent('ReactMap', () => ReactMap);

```

Is there anything else i can try?

**Comment by nsarafa** [comment]
Instead of `android:name="com.google.android.geo.API_KEY"` try using `android:name="com.google.android.maps.v2.API_KEY"`

**Comment by Newbieyh** [comment]
I am sorry to ask on this chat again.  I am getting a blank screen on my android emulator and followed all the suggestions but none helped me. So I came to this at the end. 

But cant follow the brower key thing and wipe the data thing.

I am new to programming world so these questions. 

-- Please Help

**Comment by lappalj4** [comment]
> Run "android" and install
> Extras / Google Play services
> Extras / Google Repository
> Android 6.0 (API 23) / Google APIs Intel x86 Atom System Image Rev. 12 (Make sure your emulator is using it, previous rev. did not work)

What does running "android" mean exactly? And how/where do I install these packages? Thanks.

**Comment by cokealmonacid** [comment]
Someone solve this?

**Comment by anahitsk123** [comment]
I solved this by activating 'Google Maps Android API' from https://console.developers.google.com/apis/api/maps-android-backend.googleapis.com

**Comment by jhon3rick** [comment]
react-native link react-native-maps not working in android for version react-native-maps 0.14 and 0.15, i solved install plugin manually

**Comment by kathidelacruz** [comment]
@jhon3rick Thanks! Install plugin manually works for me.

**Comment by svjchrysler** [comment]
#import <React/RCTBundleURLProvider.h> in AppDelegate.m in Xcode, give this error 'React/RCTBundleURLProvider.h' file not found.

**Comment by ghoshabhi** [comment]
@svjchrysler : Did you add `AirMaps`'s binaries too ?

**Comment by luongcongdu** [comment]
Make sure you enable Google Maps Android API

**Comment by HamiltonMultimedia** [comment]
@nicksarafa 's solution worked for me! 
THANK YOU

![screen shot 2018-05-23 at 11 56 55 pm](https://user-images.githubusercontent.com/24661651/40463819-5850e35e-5ee5-11e8-9f30-ae7bad0f85c8.png)

After changing to `android:name="com.google.android.maps.v2.API_KEY"` my map appeared immediately after reloading the Android emulator.

![screen shot 2018-05-23 at 11 56 59 pm 2](https://user-images.githubusercontent.com/24661651/40463889-d846108e-5ee5-11e8-9ed3-889378bffa7e.png)

**Comment by anastely** [comment]
Hey there, Billing account is necessary for getting google map key API?

**Comment by ErfanEbrahimii** [comment]
> Other developer in our company told me, to use "Browser or web" key, not some other key. It was a little confusing.

it work's for me on android ,
thanks a lot

**Comment by realjjaveweb** [comment]
> Hey there, Billing account is necessary for getting google map API key?

Definitely not for getting the key - you create the API key separately and enable that API for that key, but I'm not sure whether or not billing is needed for the API to be provided.

**Comment by excelso** [comment]
> Instead of android:name="com.google.android.geo.API_KEY" try using android:name="com.google.android.maps.v2.API_KEY"

Work for me, Thanks

**Comment by nwazuo** [comment]
> Instead of `android:name="com.google.android.geo.API_KEY"` try using `android:name="com.google.android.maps.v2.API_KEY"`

This worked for me. Can someone explain why this worked though and why the `react-native-maps` package isn't outputting this by default? 

Also, how to get this to work with expo's prebuild system as AndroidManifest.xml chanes don't persist when `expo prebuild` command is used with the `--clean` option.

**Comment by nwazuo** [comment]
If you're using expo, I wrote a little local config plugin to help with this. The config plugin basically renames a metadata's name. 

Steps to use: 
1. create `withRenameMetadata.js` file in your expo project (I put mine in a ./plugin folder) with below content
```js
// withRenameMetadata.js

const { withAndroidManifest } = require('@expo/config-plugins');

function renameMetadata(androidManifest, existingName, newName) {
  const existingMetaData = androidManifest.manifest.application[0]['meta-data'];
  const metaDataIndex = existingMetaData.findIndex(
    (meta) => meta['$']['android:name'] === existingName
  );

  if (metaDataIndex !== -1) {
    existingMetaData[metaDataIndex]['$']['android:name'] = newName;
  } else {
    console.warn(`Meta-data with name ${existingName} not found`);
  }
  return androidManifest;
};

module.exports = function withRenameMetadata(config, { existingName, newName }) {
  return withAndroidManifest(config, async (config) => {
    const androidManifest = config.modResults;
    config.modResults = renameMetadata(androidManifest, existingName, newName);
    return config;
  });
};
```

2. Add plugin to your app.json, app.config.json or app.config.js `plugin` field
```js
// app.config.js

{
  ...,
  plugins: [
    ...,
    [
      // See - https://github.com/react-native-maps/react-native-maps/issues/176
      './plugins/withRenameMetadata.js',
      {
        existingName: 'com.google.android.geo.API_KEY',
        newName: 'com.google.android.maps.v2.API_KEY'
      }
    ],
  ]
}
```

3. Run `expo prebuild` and look into `android/app/src/main/AndroidManifest.xml` to confirm change (Your git changes may also show this)

Hope this helps🎉.

**Comment by blwinters** [comment]
Regarding `com.google.android.maps.v2.API_KEY`, that's not the key [currently recommended](https://developers.google.com/maps/documentation/android-sdk/config#step_3_add_your_api_key_to_the_project) by Google. It's only there for backwards compatibility, but I wonder if the API key's restrictions are evaluated differently if you use that name (while the real issue is a misconfigured API key).

In my case, I had changed the tooling for building and signing our app, so I needed to [get the new SHA1 hash](https://stackoverflow.com/questions/61119983/how-do-i-get-sha-1-certificate-in-expo) and add it to the existing API key in the [Google Cloud console](https://console.cloud.google.com/google/maps-apis/credentials).
