### ISSUE TITLE
RN 0.29 ios header issue

### ISSUE THREAD

**Issue by weixingsun** [lelandrichardson/react-native-maps#371]
should we change
AIRMap.h   line 12
#import "React/RCTComponent.h"

AIRMapCallout.h  line 7
#import "React/RCTView.h"

to dir Views ?

**Comment by kfiroo** [comment]
Any news about this? Can't build current version with RN0.29.0..
Thanks

**Comment by nascode** [comment]
To fix, please change

AIRMap.h line 12
From #import <React/RCTComponent.h>
To #import "RCTComponent.h"

and 

AIRMapCallout.h line 7
From #import "React/RCTView.h"
To #import "RCTView.h"

**Comment by kfiroo** [comment]
Thanks @nascode this seems to work! 👍

**Comment by kfiroo** [comment]
PR to resolve [373](https://github.com/lelandrichardson/react-native-maps/pull/373)

**Comment by kfiroo** [comment]
So apparently this PR does not **really** solve this issue as it only shifts the problem to users using Cocoapods.

When linking this lib **manually** `import`s need to be directly to the file `RCT***.h`
When using **cocoapods** `import`s need to be from react `React/RCT***.h`

@nascode @lelandrichardson @weixingsun Anyone has any input on how to resolve this?

Thanks

**Comment by jefflau** [comment]
Yeah, I still have this problem. Using the iOS MapView for now

**Comment by jmitch0901** [comment]
@nascode Thank you!

**Comment by pareekkhushboo77** [comment]
@nascode  Thankyou soo much, i have been searching for the issue since long, and this solved..:)

**Comment by npomfret** [comment]
Any news on a fix.  0.7.1 still not working with RN0.31, getting the error `'React/RCTComponent.h' file not found` on this live in AirMap.h:

`#import <React/RCTComponent.h>`

I have forked with @nascode's fix but don't understand why the main project doesn't work yet.

**Comment by GantMan** [comment]
yeah, I too would like an update on the fix from 1 month ago.

**Comment by jefflau** [comment]
+1 I'm using the iOS component whilst I wait for this.

**Comment by julien-rodrigues** [comment]
Just ran into this, this morning.. Although I updated the lib some times ago..

**Comment by kfiroo** [comment]
@npomfret @GantMan @jefflau @julien-rodrigues 
Guys, this issue has to do with the difference between installing this lib using `cocoapods` and `manual linking` so please make sure to specify how you installed it so we can help sort it out.

Thanks :)

**Comment by julien-rodrigues** [comment]
manual for me :) Had to change the imports

**Comment by npomfret** [comment]
I don't use cocapods, I use `rpm link` (well now its `react-native link` i think).  I think cocapods might be used less commonly.

**Comment by jefflau** [comment]
I also used rnpm link

Sent from my iPhone

On Aug 13, 2016, at 6:43 PM, Nick Pomfret <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't use cocapods, I use rpm link (well now its react-native link i think). I think cocapods might be used less commonly.

-

**Comment by kfiroo** [comment]
I also used `manual linking` and submitted the pull PR above that got it to work.

@lelandrichardson do we still have a problem with `cocoapods` installs?

**Comment by npomfret** [comment]
Feels like most people are manually linking (or using `rnpm link` / `react-native link`).  Would it be possible to revert the change that broke manually linking and come up with another solution for cocapods?

**Comment by Exilz** [comment]
Same here, I cannot use this plugin on iOS. I installed it with `react-native link` (latest version).
Imports look fine, but I cannot build because of this error `no visible @interface for rctimageloader`.

Anyone with the same issue ?

**Comment by kfiroo** [comment]
I also installed using `manual linking` and everything works fine, what am I missing?

**Comment by Exilz** [comment]
@kfiroo it's related to PR #456 sorry for reporting this here.

**Comment by esutton** [comment]
Is there a solution to work-around **No visible @interface for 'RCTImageLoader'** 

@Exilz did you find solution?

Manual link did not help.

I removed path prefix from both both: 
```
AIRMap.h line 12
#import "React/RCTComponent.h"

```
and
```
AIRMapCallout.h line 7
#import "React/RCTView.h"
```

I get following error in **AIRMapMarker.m**

`/Users/edward3/Documents/projects/react-native/field-planner-mobile/node_modules/react-native-maps/ios/AirMaps/AIRMapMarker.m:212:58: No visible @interface for 'RCTImageLoader' declares the selector 'loadImageWithTag:size:scale:resizeMode:progressBlock:completionBlock:'`

**Comment by esutton** [comment]
Never mind, found solution to **No visible @interface for 'RCTImageLoader'** here:

https://github.com/lelandrichardson/react-native-maps/pull/456

**Comment by simonmitchell** [comment]
Also manually linking and running into this error. This is why I have a massive amount of distaste for CocoaPods. Agree with others thoughts that a lot more people are manually linking or using rnpm link.

**Comment by npomfret** [comment]
I agree.  Especially as 'manual' linking is built into the react-native command line now.  Can we please get the PODS change reverted?

**Comment by chocnut** [comment]
how can we fix this?

**Comment by richeterre** [comment]
This seems to be fixed in react-native-maps version 0.8.0 👍

**Comment by spikebrehm** [comment]
I just released 0.8.0, which fixes this issue.

**Comment by s-lee** [comment]
I still have this problem. I am using 0.8.0 release with RN 0.32.0.

**Comment by kfiroo** [comment]
@s-lee are you using `cocoapods` or `manual linking`?

**Comment by s-lee** [comment]
@kfiroo I am using cocoapods. Also, I checked all the changes need to be made when linking manually.

**Comment by spikebrehm** [comment]
@s-lee are you sure? 0.8.0 should have fixed that

**Comment by s-lee** [comment]
@spikebrehm yes, I was using 0.8.0 release with RN 0.32.0.
I just tested with react(15.3.1), react-native(0.33.0) and react-native-maps(0.8.2), and it fixed this issue 👍

**Comment by swyna52** [comment]
Here I'm still having the issue while using react(15.3.1), react-native(0.33.0) and react-native-maps(0.8.2). The two header files are already patched. Tried both cocoapods and manual linking.

**Comment by arashbi** [comment]
I still experience the same issue in 0.10.1.

**Comment by dazwiafl** [comment]
+1 on 0.10.1

**Comment by jjzazuet** [comment]
+1 `"version": "0.10.1"`

**Comment by GantMan** [comment]
Just experienced this on 10.2, and completely broken latest installs of our open source project :(

**Comment by soorajvnair** [comment]
Yes i experienced this too in the latest version.

**Comment by spikebrehm** [comment]
Can someone please provide a reproducible test case for this, such as a link to a repo for a minimal app that displays this error? We're not able to reproduce.

**Comment by spikebrehm** [comment]
@GantMan @soorajvnair can you paste the exact error you're seeing?

**Comment by GantMan** [comment]
0.11.0 fixed this.

**Comment by MaheshNandam** [comment]
react - 16.0.0
react-native - 0.54

'React/RCTNetworking.h' file not found, did anyone resolve this?

**Comment by rborn** [comment]
@MaheshNandam don't post the same question in multiple places.

**Comment by MaheshNandam** [comment]
hey @rborn, placing the same question in multiple places is just to get a reply, don't mind.

Indeed, I have tried #import "RCTNetworking.h", but still haven't get the solution, 

do you have any idea to solve this?

**Comment by rborn** [comment]
While you try to get a reply, people subscribed to the repo will get multiple notifications/emails because of this, so please don't do it.

It's a setup issue, try to set up the project as specified in the installation instructions.

**Comment by kevinzhangftw** [comment]
hi, i am having the same problem 
`#import <React/RCTNetworking.h>` file not found
using cocoapods 

```
Last login: Thu Jun 28 15:15:48 on ttys007
Hello Kevin
env: node: No such file or directory
bglocation $ ls
App.js       App.test.js  README.md    android      app.json     index.js     ios          node_modules package.json yarn.lock
bglocation $ cd ios
ios $ gem install cocoapods
Fetching: concurrent-ruby-1.0.5.gem (100%)
Successfully installed concurrent-ruby-1.0.5
Fetching: i18n-0.9.5.gem (100%)
Successfully installed i18n-0.9.5
Fetching: thread_safe-0.3.6.gem (100%)
Successfully installed thread_safe-0.3.6
Fetching: tzinfo-1.2.5.gem (100%)
Successfully installed tzinfo-1.2.5
Fetching: activesupport-4.2.10.gem (100%)
Successfully installed activesupport-4.2.10
Fetching: nap-1.1.0.gem (100%)
Successfully installed nap-1.1.0
Fetching: fuzzy_match-2.0.4.gem (100%)
Successfully installed fuzzy_match-2.0.4
Fetching: cocoapods-core-1.5.3.gem (100%)
Successfully installed cocoapods-core-1.5.3
Fetching: claide-1.0.2.gem (100%)
Successfully installed claide-1.0.2
Fetching: cocoapods-deintegrate-1.0.2.gem (100%)
Successfully installed cocoapods-deintegrate-1.0.2
Fetching: cocoapods-downloader-1.2.1.gem (100%)
Successfully installed cocoapods-downloader-1.2.1
Fetching: cocoapods-plugins-1.0.0.gem (100%)
Successfully installed cocoapods-plugins-1.0.0
Fetching: cocoapods-search-1.0.0.gem (100%)
Successfully installed cocoapods-search-1.0.0
Fetching: cocoapods-stats-1.0.0.gem (100%)
Successfully installed cocoapods-stats-1.0.0
Fetching: netrc-0.11.0.gem (100%)
Successfully installed netrc-0.11.0
Fetching: cocoapods-trunk-1.3.0.gem (100%)
Successfully installed cocoapods-trunk-1.3.0
Fetching: cocoapods-try-1.1.0.gem (100%)
Successfully installed cocoapods-try-1.1.0
Fetching: molinillo-0.6.5.gem (100%)
Successfully installed molinillo-0.6.5
Fetching: atomos-0.1.2.gem (100%)
Successfully installed atomos-0.1.2
Fetching: CFPropertyList-3.0.0.gem (100%)
Successfully installed CFPropertyList-3.0.0
Fetching: colored2-3.1.2.gem (100%)
Successfully installed colored2-3.1.2
Fetching: nanaimo-0.2.5.gem (100%)
Successfully installed nanaimo-0.2.5
Fetching: xcodeproj-1.5.9.gem (100%)
Successfully installed xcodeproj-1.5.9
Fetching: escape-0.0.4.gem (100%)
Successfully installed escape-0.0.4
Fetching: fourflusher-2.0.1.gem (100%)
Successfully installed fourflusher-2.0.1
Fetching: gh_inspector-1.1.3.gem (100%)
Successfully installed gh_inspector-1.1.3
Fetching: ruby-macho-1.2.0.gem (100%)
Successfully installed ruby-macho-1.2.0
Fetching: cocoapods-1.5.3.gem (100%)
Successfully installed cocoapods-1.5.3
Parsing documentation for concurrent-ruby-1.0.5
Installing ri documentation for concurrent-ruby-1.0.5
Parsing documentation for i18n-0.9.5
Installing ri documentation for i18n-0.9.5
Parsing documentation for thread_safe-0.3.6
Installing ri documentation for thread_safe-0.3.6
Parsing documentation for tzinfo-1.2.5
Installing ri documentation for tzinfo-1.2.5
Parsing documentation for activesupport-4.2.10
Installing ri documentation for activesupport-4.2.10
Parsing documentation for nap-1.1.0
Installing ri documentation for nap-1.1.0
Parsing documentation for fuzzy_match-2.0.4
Installing ri documentation for fuzzy_match-2.0.4
Parsing documentation for cocoapods-core-1.5.3
Installing ri documentation for cocoapods-core-1.5.3
Parsing documentation for claide-1.0.2
Installing ri documentation for claide-1.0.2
Parsing documentation for cocoapods-deintegrate-1.0.2
Installing ri documentation for cocoapods-deintegrate-1.0.2
Parsing documentation for cocoapods-downloader-1.2.1
Installing ri documentation for cocoapods-downloader-1.2.1
Parsing documentation for cocoapods-plugins-1.0.0
Installing ri documentation for cocoapods-plugins-1.0.0
Parsing documentation for cocoapods-search-1.0.0
Installing ri documentation for cocoapods-search-1.0.0
Parsing documentation for cocoapods-stats-1.0.0
Installing ri documentation for cocoapods-stats-1.0.0
Parsing documentation for netrc-0.11.0
Installing ri documentation for netrc-0.11.0
Parsing documentation for cocoapods-trunk-1.3.0
Installing ri documentation for cocoapods-trunk-1.3.0
Parsing documentation for cocoapods-try-1.1.0
Installing ri documentation for cocoapods-try-1.1.0
Parsing documentation for molinillo-0.6.5
Installing ri documentation for molinillo-0.6.5
Parsing documentation for atomos-0.1.2
Installing ri documentation for atomos-0.1.2
Parsing documentation for CFPropertyList-3.0.0
Installing ri documentation for CFPropertyList-3.0.0
Parsing documentation for colored2-3.1.2
Installing ri documentation for colored2-3.1.2
Parsing documentation for nanaimo-0.2.5
Installing ri documentation for nanaimo-0.2.5
Parsing documentation for xcodeproj-1.5.9
Installing ri documentation for xcodeproj-1.5.9
Parsing documentation for escape-0.0.4
Installing ri documentation for escape-0.0.4
Parsing documentation for fourflusher-2.0.1
Installing ri documentation for fourflusher-2.0.1
Parsing documentation for gh_inspector-1.1.3
Installing ri documentation for gh_inspector-1.1.3
Parsing documentation for ruby-macho-1.2.0
Installing ri documentation for ruby-macho-1.2.0
Parsing documentation for cocoapods-1.5.3
Installing ri documentation for cocoapods-1.5.3
Done installing documentation for concurrent-ruby, i18n, thread_safe, tzinfo, activesupport, nap, fuzzy_match, cocoapods-core, claide, cocoapods-deintegrate, cocoapods-downloader, cocoapods-plugins, cocoapods-search, cocoapods-stats, netrc, cocoapods-trunk, cocoapods-try, molinillo, atomos, CFPropertyList, colored2, nanaimo, xcodeproj, escape, fourflusher, gh_inspector, ruby-macho, cocoapods after 22 seconds
28 gems installed
ios $ pod setup
Setting up CocoaPods master repo
  $ /usr/bin/git clone https://github.com/CocoaPods/Specs.git master --progress
  Cloning into 'master'...
  remote: Counting objects: 2251120, done.
  remote: Compressing objects: 100% (434/434), done.
  remote: Total 2251120 (delta 188), reused 35 (delta 35), pack-reused 2250633
  Receiving objects: 100% (2251120/2251120), 549.87 MiB | 8.91 MiB/s, done.
  Resolving deltas: 100% (1290661/1290661), done.
  Checking out files: 100% (248494/248494), done.
Setup completed
ios $ ls
bglocation           bglocation-tvOS      bglocation-tvOSTests bglocation.xcodeproj bglocationTests      build
ios $ cd ..
bglocation $ ls
App.js       App.test.js  README.md    android      app.json     index.js     ios          node_modules package.json yarn.lock
bglocation $ cd ios
ios $ ls
bglocation           bglocation-tvOS      bglocation-tvOSTests bglocation.xcodeproj bglocationTests      build
ios $ cd bglocation
bglocation $ ls
AppDelegate.h   AppDelegate.m   Base.lproj      Images.xcassets Info.plist      main.m
bglocation $ cd ..
ios $ ls
bglocation           bglocation-tvOS      bglocation-tvOSTests bglocation.xcodeproj bglocationTests      build
ios $ cd build
build $ ls
Build               Index               ModuleCache.noindex info.plist
build $ cd ..
ios $ ld
ld: no object files specified
ios $ lf
-bash: lf: command not found
ios $ ls
bglocation           bglocation-tvOS      bglocation-tvOSTests bglocation.xcodeproj bglocationTests      build
ios $ cd ..
bglocation $ ls
App.js       App.test.js  README.md    android      app.json     index.js     ios          node_modules package.json yarn.lock
bglocation $ cd node_modules/
node_modules $ ls
@babel                                                  istanbul-lib-hook
abab                                                    istanbul-lib-instrument
abbrev                                                  istanbul-lib-report
absolute-path                                           istanbul-lib-source-maps
accepts                                                 istanbul-reports
acorn                                                   jest
acorn-globals                                           jest-changed-files
ajv                                                     jest-cli
align-text                                              jest-config
amdefine                                                jest-diff
ansi                                                    jest-docblock
ansi-colors                                             jest-each
ansi-cyan                                               jest-environment-jsdom
ansi-escapes                                            jest-environment-node
ansi-gray                                               jest-get-type
ansi-red                                                jest-haste-map
ansi-regex                                              jest-jasmine2
ansi-styles                                             jest-leak-detector
ansi-wrap                                               jest-matcher-utils
anymatch                                                jest-message-util
append-transform                                        jest-mock
aproba                                                  jest-react-native
arch                                                    jest-regex-util
are-we-there-yet                                        jest-resolve
argparse                                                jest-resolve-dependencies
arr-diff                                                jest-runner
arr-flatten                                             jest-runtime
arr-union                                               jest-serializer
array-equal                                             jest-snapshot
array-filter                                            jest-util
array-map                                               jest-validate
array-reduce                                            jest-watcher
array-slice                                             jest-worker
array-unique                                            js-tokens
arrify                                                  js-yaml
art                                                     jsbn
asap                                                    jsdom
asn1                                                    jsesc
assert-plus                                             json-schema
assign-symbols                                          json-schema-traverse
astral-regex                                            json-stable-stringify
async                                                   json-stringify-safe
async-limiter                                           json5
asynckit                                                jsonfile
atob                                                    jsonify
aws-sign2                                               jsprim
aws4                                                    kind-of
babel-code-frame                                        klaw
babel-core                                              lazy-cache
babel-generator                                         lcid
babel-helper-builder-binary-assignment-operator-visitor left-pad
babel-helper-builder-react-jsx                          leven
babel-helper-call-delegate                              levn
babel-helper-define-map                                 load-json-file
babel-helper-explode-assignable-expression              locate-path
babel-helper-function-name                              lodash
babel-helper-get-function-arity                         lodash.pad
babel-helper-hoist-variables                            lodash.padend
babel-helper-optimise-call-expression                   lodash.padstart
babel-helper-regex                                      lodash.sortby
babel-helper-remap-async-to-generator                   lodash.throttle
babel-helper-replace-supers                             longest
babel-helpers                                           loose-envify
babel-jest                                              lru-cache
babel-messages                                          macos-release
babel-plugin-check-es2015-constants                     make-dir
babel-plugin-external-helpers                           makeerror
babel-plugin-istanbul                                   map-cache
babel-plugin-jest-hoist                                 map-visit
babel-plugin-react-transform                            math-random
babel-plugin-syntax-async-functions                     mem
babel-plugin-syntax-class-constructor-call              merge
babel-plugin-syntax-class-properties                    merge-stream
babel-plugin-syntax-decorators                          metro
babel-plugin-syntax-do-expressions                      metro-babylon7
babel-plugin-syntax-dynamic-import                      metro-cache
babel-plugin-syntax-exponentiation-operator             metro-core
babel-plugin-syntax-export-extensions                   metro-minify-uglify
babel-plugin-syntax-flow                                metro-resolver
babel-plugin-syntax-function-bind                       metro-source-map
babel-plugin-syntax-jsx                                 micromatch
babel-plugin-syntax-object-rest-spread                  mime
babel-plugin-syntax-trailing-function-commas            mime-db
babel-plugin-transform-async-to-generator               mime-types
babel-plugin-transform-class-constructor-call           mimic-fn
babel-plugin-transform-class-properties                 min-document
babel-plugin-transform-decorators-legacy                minimatch
babel-plugin-transform-do-expressions                   minimist
babel-plugin-transform-es2015-arrow-functions           minipass
babel-plugin-transform-es2015-block-scoped-functions    minizlib
babel-plugin-transform-es2015-block-scoping             mixin-deep
babel-plugin-transform-es2015-classes                   mkdirp
babel-plugin-transform-es2015-computed-properties       morgan
babel-plugin-transform-es2015-destructuring             ms
babel-plugin-transform-es2015-for-of                    mute-stream
babel-plugin-transform-es2015-function-name             nan
babel-plugin-transform-es2015-literals                  nanomatch
babel-plugin-transform-es2015-modules-commonjs          natural-compare
babel-plugin-transform-es2015-object-super              needle
babel-plugin-transform-es2015-parameters                negotiator
babel-plugin-transform-es2015-shorthand-properties      node-fetch
babel-plugin-transform-es2015-spread                    node-int64
babel-plugin-transform-es2015-sticky-regex              node-modules-regexp
babel-plugin-transform-es2015-template-literals         node-notifier
babel-plugin-transform-es2015-unicode-regex             node-pre-gyp
babel-plugin-transform-es3-member-expression-literals   nopt
babel-plugin-transform-es3-property-literals            normalize-package-data
babel-plugin-transform-exponentiation-operator          normalize-path
babel-plugin-transform-export-extensions                npm-bundled
babel-plugin-transform-flow-strip-types                 npm-packlist
babel-plugin-transform-function-bind                    npm-run-path
babel-plugin-transform-object-assign                    npmlog
babel-plugin-transform-object-rest-spread               number-is-nan
babel-plugin-transform-react-display-name               nwsapi
babel-plugin-transform-react-jsx                        oauth-sign
babel-plugin-transform-react-jsx-source                 object-assign
babel-plugin-transform-regenerator                      object-copy
babel-plugin-transform-strict-mode                      object-keys
babel-preset-es2015-node                                object-visit
babel-preset-fbjs                                       object.getownpropertydescriptors
babel-preset-jest                                       object.omit
babel-preset-react-native                               object.pick
babel-preset-react-native-stage-0                       on-finished
babel-register                                          on-headers
babel-runtime                                           once
babel-template                                          onetime
babel-traverse                                          opn
babel-types                                             optimist
babylon                                                 optionator
balanced-match                                          options
base                                                    os-homedir
base64-js                                               os-locale
basic-auth                                              os-name
bcrypt-pbkdf                                            os-tmpdir
big-integer                                             osenv
bplist-creator                                          p-finally
bplist-parser                                           p-limit
brace-expansion                                         p-locate
braces                                                  p-try
browser-process-hrtime                                  parse-glob
browser-resolve                                         parse-json
bser                                                    parse5
buffer-from                                             parseurl
builtin-modules                                         pascalcase
bytes                                                   path-exists
cache-base                                              path-is-absolute
callsites                                               path-key
camelcase                                               path-parse
capture-exit                                            path-type
caseless                                                pegjs
center-align                                            performance-now
chalk                                                   pify
chardet                                                 pinkie
chownr                                                  pinkie-promise
ci-info                                                 pirates
class-utils                                             pkg-dir
cli-cursor                                              plist
cli-width                                               plugin-error
clipboardy                                              pn
cliui                                                   posix-character-classes
clorox                                                  prelude-ls
co                                                      preserve
cocoa-lumberjack                                        pretty-format
code-point-at                                           private
collection-visit                                        process
color-convert                                           process-nextick-args
color-name                                              promise
color-support                                           prompts
combined-stream                                         prop-types
commander                                               pseudomap
commondir                                               psl
compare-versions                                        punycode
component-emitter                                       qs
compressible                                            randomatic
compression                                             range-parser
concat-map                                              rc
concat-stream                                           react
connect                                                 react-clone-referenced-element
console-control-strings                                 react-deep-force-update
convert-source-map                                      react-devtools-core
copy-descriptor                                         react-is
core-js                                                 react-native
core-util-is                                            react-native-background-fetch
create-react-class                                      react-native-background-geolocation
cross-spawn                                             react-proxy
cssom                                                   react-test-renderer
cssstyle                                                react-timer-mixin
dashdash                                                react-transform-hmr
data-urls                                               read-pkg
debug                                                   read-pkg-up
decamelize                                              readable-stream
decode-uri-component                                    realpath-native
deep-extend                                             regenerate
deep-is                                                 regenerator-runtime
default-require-extensions                              regenerator-transform
define-properties                                       regex-cache
define-property                                         regex-not
delayed-stream                                          regexpu-core
delegates                                               regjsgen
denodeify                                               regjsparser
depd                                                    remove-trailing-separator
destroy                                                 repeat-element
detect-indent                                           repeat-string
detect-libc                                             repeating
detect-newline                                          request
diff                                                    request-promise-core
dom-walk                                                request-promise-native
domexception                                            require-directory
ecc-jsbn                                                require-main-filename
ee-first                                                resolve
encodeurl                                               resolve-cwd
encoding                                                resolve-from
envinfo                                                 resolve-url
error-ex                                                restore-cursor
errorhandler                                            ret
es-abstract                                             right-align
es-to-primitive                                         rimraf
escape-html                                             rsvp
escape-string-regexp                                    run-async
escodegen                                               rx-lite
eslint-plugin-react-native                              rx-lite-aggregates
eslint-plugin-react-native-globals                      safe-buffer
esprima                                                 safe-regex
estraverse                                              safer-buffer
esutils                                                 sane
etag                                                    sax
event-target-shim                                       semver
eventemitter3                                           send
exec-sh                                                 serialize-error
execa                                                   serve-static
exit                                                    set-blocking
expand-brackets                                         set-value
expand-range                                            setimmediate
expect                                                  setprototypeof
extend                                                  shebang-command
extend-shallow                                          shebang-regex
external-editor                                         shell-quote
extglob                                                 shellwords
extsprintf                                              signal-exit
fancy-log                                               simple-plist
fast-deep-equal                                         sisteransi
fast-json-stable-stringify                              slash
fast-levenshtein                                        slide
fast-plist                                              snapdragon
fb-watchman                                             snapdragon-node
fbjs                                                    snapdragon-util
fbjs-scripts                                            source-map
figures                                                 source-map-resolve
filename-regex                                          source-map-support
fileset                                                 source-map-url
fill-range                                              spdx-correct
finalhandler                                            spdx-exceptions
find-cache-dir                                          spdx-expression-parse
find-up                                                 spdx-license-ids
for-in                                                  split-string
for-own                                                 sprintf-js
foreach                                                 sshpk
forever-agent                                           stack-utils
form-data                                               stacktrace-parser
fragment-cache                                          static-extend
fresh                                                   statuses
fs-extra                                                stealthy-require
fs-minipass                                             stream-buffers
fs.realpath                                             string-length
fsevents                                                string-width
function-bind                                           string_decoder
gauge                                                   strip-ansi
get-caller-file                                         strip-bom
get-stream                                              strip-eof
get-value                                               strip-json-comments
getpass                                                 supports-color
glob                                                    symbol-tree
glob-base                                               tar
glob-parent                                             temp
global                                                  test-exclude
globals                                                 throat
graceful-fs                                             through
growly                                                  through2
handlebars                                              time-stamp
har-schema                                              tmp
har-validator                                           tmpl
has                                                     to-fast-properties
has-ansi                                                to-object-path
has-flag                                                to-regex
has-unicode                                             to-regex-range
has-value                                               tough-cookie
has-values                                              tr46
home-or-tmp                                             trim-right
hosted-git-info                                         tunnel-agent
html-encoding-sniffer                                   tweetnacl
http-errors                                             type-check
http-signature                                          typedarray
iconv-lite                                              ua-parser-js
ignore-walk                                             uglify-es
image-size                                              uglify-js
import-local                                            uglify-to-browserify
imurmurhash                                             ultron
inflight                                                union-value
inherits                                                unpipe
ini                                                     unset-value
inquirer                                                urix
invariant                                               use
invert-kv                                               util-deprecate
is-accessor-descriptor                                  util.promisify
is-arrayish                                             utils-merge
is-buffer                                               uuid
is-builtin-module                                       validate-npm-package-license
is-callable                                             vary
is-ci                                                   verror
# Uncomment the next line to define a global platform for your project
is-data-descriptor                                      w3c-hr-time
is-date-object                                          walker
is-descriptor                                           watch
is-dotfile                                              webidl-conversions
target 'bglocation-tvOS' do
is-equal-shallow                                        whatwg-encoding
is-extendable                                           whatwg-fetch
is-extglob                                              whatwg-mimetype
is-finite                                               whatwg-url
is-fullwidth-code-point                                 which
is-generator-fn                                         which-module
is-glob                                                 wide-align
is-number                                               win-release
is-plain-object                                         window-size
is-posix-bracket                                        wordwrap
is-primitive                                            wrap-ansi
is-promise                                              wrappy
is-regex                                                write-file-atomic
is-stream                                               ws
is-symbol                                               xcode
is-typedarray                                           xml-name-validator
is-utf8                                                 xmlbuilder
is-windows                                              xmldoc
isarray                                                 xmldom
isexe                                                   xpipe
isobject                                                xtend
isomorphic-fetch                                        y18n
isstream                                                yallist
istanbul-api                                            yargs
istanbul-lib-coverage                                   yargs-parser
node_modules $ cd ..
bglocation $ ls
App.js       App.test.js  README.md    android      app.json     index.js     ios          node_modules package.json yarn.lock
bglocation $ cd ios
ios $ ls
bglocation           bglocation-tvOS      bglocation-tvOSTests bglocation.xcodeproj bglocationTests      build
ios $ pod init
ios $ ls
Podfile              bglocation           bglocation-tvOS      bglocation-tvOSTests bglocation.xcodeproj bglocationTests      build
ios $ vim Podfile
ios $ pod install
Analyzing dependencies
[!] The target `bglocation-tvOSTests` is declared twice.
ios $ vim Podfile
ios $ pod install
Analyzing dependencies
Fetching podspec for `RNBackgroundFetch` from `../node_modules/react-native-background-fetch`
Fetching podspec for `RNBackgroundGeolocation` from `../node_modules/react-native-background-geolocation`
Fetching podspec for `React` from `../node_modules/react-native`
[!] Unable to find a specification for `yoga (= 0.55.4.React)` depended upon by `React/Core`

[!] Automatically assigning platform `ios` with version `8.0` on target `bglocation` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `tvos` with version `9.2` on target `bglocation-tvOS` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
ios $ ls
Podfile              bglocation           bglocation-tvOSTests bglocationTests
Pods                 bglocation-tvOS      bglocation.xcodeproj build
ios $ cd ..
bglocation $ ls
App.js       App.test.js  README.md    android      app.json     index.js     ios          node_modules package.json yarn.lock
bglocation $ ls
App.js       App.test.js  README.md    android      app.json     index.js     ios          node_modules package.json yarn.lock
bglocation $ pod install
[!] No `Podfile' found in the project directory.
# Uncomment the next line to define a global platform for your project
bglocation $ cd ios
ios $ pod install
Analyzing dependencies
Fetching podspec for `RNBackgroundFetch` from `../node_modules/react-native-background-fetch`
Fetching podspec for `RNBackgroundGeolocation` from `../node_modules/react-native-background-geolocation`
Fetching podspec for `React` from `../node_modules/react-native`
[!] Unable to find a specification for `yoga (= 0.55.4.React)` depended upon by `React/Core`

[!] Automatically assigning platform `ios` with version `8.0` on target `bglocation` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `tvos` with version `9.2` on target `bglocation-tvOS` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
ios $ ls
Podfile              bglocation           bglocation-tvOSTests bglocationTests
Pods                 bglocation-tvOS      bglocation.xcodeproj build
ios $ vim Podfile
ios $ pod install
Analyzing dependencies
Fetching podspec for `RNBackgroundFetch` from `../node_modules/react-native-background-fetch`
Fetching podspec for `RNBackgroundGeolocation` from `../node_modules/react-native-background-geolocation`
Fetching podspec for `React` from `../node_modules/react-native`
[!] Unable to find a specification for `yoga (= 0.55.4.React)` depended upon by `React/Core`

[!] Automatically assigning platform `ios` with version `8.0` on target `bglocation` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `tvos` with version `9.2` on target `bglocation-tvOS` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
ios $ cd ..
bglocation $ ls
App.js       App.test.js  README.md    android      app.json     index.js     ios          node_modules package.json yarn.lock
bglocation $ cd ios
ios $ ls
Podfile              bglocation           bglocation-tvOSTests bglocationTests
Pods                 bglocation-tvOS      bglocation.xcodeproj build
ios $ cim Podfile
-bash: cim: command not found
ios $ vim Podfile
ios $ pod install
Analyzing dependencies
Fetching podspec for `RNBackgroundFetch` from `../node_modules/react-native-background-fetch`
Fetching podspec for `RNBackgroundGeolocation` from `../node_modules/react-native-background-geolocation`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
Downloading dependencies
Installing CocoaLumberjack (3.4.2)
Installing RNBackgroundFetch (2.4.3)
Installing RNBackgroundGeolocation (2.12.2)
Installing React (0.55.4)
Installing yoga (0.55.4.React)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `bglocation.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 5 total pods installed.

[!] Automatically assigning platform `ios` with version `8.0` on target `bglocation` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `tvos` with version `9.2` on target `bglocation-tvOS` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] The `bglocation [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-bglocation/Pods-bglocation.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `bglocation [Release]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-bglocation/Pods-bglocation.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `bglocation-tvOS [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-bglocation-tvOS/Pods-bglocation-tvOS.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `bglocation-tvOS [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-bglocation-tvOS/Pods-bglocation-tvOS.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `bglocation-tvOSTests [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-bglocation-tvOST# Uncomment the next line to define a global platform for your project
ests/Pods-bglocation-tvOSTests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

# Uncomment the next line to define a global platform for your project
[!] The `bglocation-tvOSTests [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-bglocation-tvOSTests/Pods-bglocation-tvOSTests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `bglocation-tvOSTests [Release]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-bglocation-tvOSTests/Pods-bglocation-tvOSTests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `bglocation-tvOSTests [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-bglocation-tvOSTests/Pods-bglocation-tvOSTests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `bglocationTests [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-bglocationTests/Pods-bglocationTests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `bglocationTests [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-bglocationTests/Pods-bglocationTests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `bglocationTests [Release]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-bglocationTests/Pods-bglocationTests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `bglocationTests [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-bglocationTests/Pods-bglocationTests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
ios $ vim Podfile
ios $ ls
Podfile                Pods                   bglocation-tvOS        bglocation.xcodeproj   bglocationTests
Podfile.lock           bglocation             bglocation-tvOSTests   bglocation.xcworkspace build
ios $ vim Podfile
ios $ pod install
Analyzing dependencies
Fetching podspec for `RNBackgroundFetch` from `../node_modules/react-native-background-fetch`
Fetching podspec for `RNBackgroundGeolocation` from `../node_modules/react-native-background-geolocation`
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `yoga` from `../node_modules/react-native/ReactCommon/yoga`
Downloading dependencies
Using CocoaLumberjack (3.4.2)
Using RNBackgroundFetch (2.4.3)
Using RNBackgroundGeolocation (2.12.2)
Installing React 0.55.4
Using yoga (0.55.4.React)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 5 dependencies from the Podfile and 5 total pods installed.

[!] Automatically assigning platform `ios` with version `8.0` on target `bglocation` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `tvos` with version `9.2` on target `bglocation-tvOS` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] The `bglocation [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-bglocation/Pods-bglocation.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `bglocation [Release]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-bglocation/Pods-bglocation.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `bglocation-tvOS [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-bglocation-tvOS/Pods-bglocation-tvOS.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `bglocation-tvOS [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-bglocation-tvOS/Pods-bglocation-tvOS.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `bglocation-tvOSTests [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-bglocation-tvOSTests/Pods-bglocation-tvOSTests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bglocation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bglocation
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
#https://github.com/facebook/react-native/issues/13046
pod 'React', :path => '../node_modules/react-native'
  pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'
  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'
pod 'React', :path => '../node_modules/react-native', :subspecs => ['DevSupport']
  target 'bglocation-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bglocationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'bglocation-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bglocation-tvOS

 # target 'bglocation-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
  #end

end
```
